// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbjxpV7Cp6AkXXBtz961BRq4evnHaYe60',
    appId: '1:783930733493:web:20323cfb01955b95105ffc',
    messagingSenderId: '783930733493',
    projectId: 'studymap-6c7b8',
    authDomain: 'studymap-6c7b8.firebaseapp.com',
    storageBucket: 'studymap-6c7b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGXwTdfsCZ3JXhbhg0JU5Dbj_JV3wBEGs',
    appId: '1:783930733493:android:cbbdf72ddb68acff105ffc',
    messagingSenderId: '783930733493',
    projectId: 'studymap-6c7b8',
    storageBucket: 'studymap-6c7b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMpo88po8FKry5Uj9Vinu_Vw5K3lJxccs',
    appId: '1:783930733493:ios:16bb7e7d31788754105ffc',
    messagingSenderId: '783930733493',
    projectId: 'studymap-6c7b8',
    storageBucket: 'studymap-6c7b8.firebasestorage.app',
    iosClientId: '783930733493-m2uqasmm68flt2ov88ji66ag0jtlpgcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.studymap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMpo88po8FKry5Uj9Vinu_Vw5K3lJxccs',
    appId: '1:783930733493:ios:16bb7e7d31788754105ffc',
    messagingSenderId: '783930733493',
    projectId: 'studymap-6c7b8',
    storageBucket: 'studymap-6c7b8.firebasestorage.app',
    iosClientId: '783930733493-m2uqasmm68flt2ov88ji66ag0jtlpgcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.studymap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbjxpV7Cp6AkXXBtz961BRq4evnHaYe60',
    appId: '1:783930733493:web:20cc63bd805fcc86105ffc',
    messagingSenderId: '783930733493',
    projectId: 'studymap-6c7b8',
    authDomain: 'studymap-6c7b8.firebaseapp.com',
    storageBucket: 'studymap-6c7b8.firebasestorage.app',
  );
}
